//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystemV1._0__Beta_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int employeeID { get; set; }
        public string plateNum { get; set; }
        public string make { get; set; }
        public string modle { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
